---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tenant-blue-ingress-allow-web
  namespace: multinetpolicy-configs
  labels:
    multinetpolicy-nad: tenant-blue
    multinetpolicy-type: ingress
data:
  rules: |
    [
      {
        "protocol": "TCP",
        "port": "443",
        "cidr": "10.0.0.0/24",
        "except": ["10.0.0.5/32", "10.0.0.6/32"]
      },
      {
        "protocol": "TCP",
        "port": "8080",
        "cidr": "172.16.0.0/16"
      }
    ]
