---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tenant-blue-ingress-allow-api
  namespace: multinetpolicy-configs
  labels:
    multinetpolicy-nad: tenant-blue
    multinetpolicy-type: ingress
data:
  rules: |
    [
      {
        "protocol": "TCP",
        "port": "9090",
        "cidr": "10.1.0.0/16"
      }
    ]
