---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tenant-blue-ns-web-ingress-allow-https
  namespace: multinetpolicy-configs
  labels:
    multinetpolicy-nad: tenant-blue
    multinetpolicy-type: ingress
    multinetpolicy-namespace: web-frontend
data:
  rules: |
    [
      {
        "protocol": "TCP",
        "port": "4430",
        "cidr": "0.0.0.0/0"
      }
    ]
