---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
  - ./set-clusterset-references.yml

configurations:
  - ./policyset-namereference.yml
  - ./namespace-namereference.yml

patches:
  - target:
      kind: Policy
    patch: |
      - op: add
        path: /spec/copyPolicyMetadata
        value: false
