---
apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: set-clusterset-label
replacements:
  - source:
      kind: ManagedClusterSet
      fieldPath: metadata.name
    targets:
      - select:
          kind: ManagedCluster
          name: local-cluster
        fieldPaths:
          - metadata.labels.[cluster.open-cluster-management.io/clusterset]

      - select:
          kind: Placement
        fieldPaths:
          - spec.clusterSets.0

      - select:
          kind: ManagedClusterSetBinding
        fieldPaths:
          - spec.clusterSet
          - metadata.name
