---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: multinetwork-policies-dev

transformers:
  - kustomize-configs/policyset-suffixer.yml

resources:
  - managedclusterset.yml
  - ../../policies/

components:
  - ../../kustomize-configs/
